[alembic]
script_location = alembic
sqlalchemy.url = postgresql+psycopg2://postgres:your_password@localhost:5432/mental_health_platform
prepend_sys_path = .
version_path_separator = os
version_locations = alembic/versions
file_template = %%(year)d%%(month)02d%%(day)02d_%%(hour)02d%%(minute)02d_%%(slug)s
output_encoding = utf-8

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
